### ISSUE TITLE
Weight export doesn't work with curves

### ISSUE THREAD

**Issue by Enrique-Caballero** [theRussetPotato/weights_editor#10]
Can't export weights on curves, I assume this also means that we can't import weights on curves. Would be a valuable addition to round out this great tool.

Error follows:

    return om2.MFnMesh(mdag_path)
ValueError: object is incompatible with MFnMesh constructor

**Comment by theRussetPotato** [comment]
@Enrique-Caballero Fixed it so the exporter and importer supports nurbsCurve types now.
