### ISSUE TITLE
Presets increments

### ISSUE THREAD

**Issue by CarlosValcarcel** [theRussetPotato/weights_editor#2]
Hello,
Thank you so much for developing this tool. I am a Softimage user and I really really miss Softimage's skinning workflow. Specially the weight editor.
By testing your tool, I notice a few things that I would like to give feedback on:

- The lowest preset for the ADD is too high. I think that the lowest increment should be 0.01
- The step of the spinner box is too high. I think that it is set to 10.
- Not sure how to use the spinner box. The value seems to be applied when pressing enter, but how to apply it multiple times? It feels like it is missing an "apply" button or an "ADD" and a "SUBTRACT" button that uses the spinner value.
- It would be awesome if there could be a slider like in the softimage weight editor. This is the feature that I miss the most. Being able to use a slider to add or remove weighting while seeing the result in real-time. And having that slider reset to zero when we change influence. (As an example, this is super useful when fine tweaking the weights of an edge loop around an elbow)
- The weight locking seems to work per joints, but it would be awesome if it could work per cell of the table. (This is probably a limitation of Maya I suppose)
- I do not know if it is possible, but it would be great when using the Softimage color theme if the colors on the polygons could use the weight values. In softimage it looks like the point colors are 100% of the main influence color, but the color on the polygons are weighted. This allows a better visualization of the weights. It is easier to see smoothed areas.

That is all that I can think of right now.
Great work! Thanks so much for this tool!

**Comment by theRussetPotato** [comment]
Hey Carlos, thanks so much for the feedback.

> The lowest preset for the ADD is too high. I think that the lowest increment should be 0.01

I'll include a way so you can edit these preset values to whatever you like. This way it gives the user more flexibility.

> The step of the spinner box is too high. I think that it is set to 10.

Agreed

> Not sure how to use the spinner box. The value seems to be applied when pressing enter, but how to apply it multiple times?

When you click on it to give it focus, you can simply hit enter as many times as you like to apply it, although I do see why this can be confusing. I see this more as a UX issue.

> It would be awesome if there could be a slider like in the softimage weight editor.

Not something I can get right away but it's a cool idea. Keep an eye out for future releases :)

> The weight locking seems to work per joints, but it would be awesome if it could work per cell of the table.

I suspect with the current methods I'm using to edit weights I wouldn't be able to pull this off.

> I do not know if it is possible, but it would be great when using the Softimage color theme if the colors on the polygons could use the weight values.

I think you mean to have it like NG skin tools does it? With a few tweaks I think it's possible.

Thanks for the great suggestions!

**Comment by CarlosValcarcel** [comment]
> I think you mean to have it like NG skin tools does it? With a few tweaks I think it's possible.

Yes, but keeping the softimage color scheme. The NG skin colors are really hard to work with. The fact that they use white for the active influence makes it really hard to see what you are doing. Softimage does not change color for the active influence. It is better in my opinion because your visual memory of the weighting does not get reset every time you select a new influence. So to summarize, on the points it is a solid color of the main influence on that point. On the polygons the color is smoothed according to the weight values (not just the main influence).

Thanks again!

**Comment by theRussetPotato** [comment]
Addressed a few of these notes on release v2.1.0:

- Softimage colors are no longer solid, and now are shaded by their weight values
- Lowered add preset buttons to 0.01
- Fixed preset spin boxes min, max, and step values

**Comment by CarlosValcarcel** [comment]
Thanks so much for this update :)
Sorry, I couldn't test it before. It is working great :)

**Comment by theRussetPotato** [comment]
Added dialog where you can edit and customize all preset buttons to your liking.

**Comment by CarlosValcarcel** [comment]
Cool! Thanks for the update!
