### ISSUE TITLE
Flood to closest doesn't undo properly

### ISSUE THREAD

**Issue by Enrique-Caballero** [theRussetPotato/weights_editor#6]
Pressing flood to closest, and then pressing the undo button on the menu doesn't work properly. It seems to change the weights on the weight table but it doesn't update the geometry in the viewport.

Tested on Maya 2022

**Comment by theRussetPotato** [comment]
The latest changes has fixed this bug. I'll close this when it merges to the master branch.

**Comment by theRussetPotato** [comment]
This has been addressed in release v2.3.0
